---
version: '3.10'

services:
  app:
    build: ./app
    ports:
         - '5000:5000'
    working_dir: /app
    # defining the environmental environments for mysql
    env_file: ./.env.py
    # network link to db container
    #volumes: 
    #  - /csv_files_origin_offline:/app/csv_files_origin_offline 
    links:
      - db
    deploy:
      restart_policy:
        condition: any

  db:
    image: mysql:latest
    env_file: ./.env.py
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3307:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # create a read only vol in the docker containet
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro

